//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProjectRestaurangMVC01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public Reservation()
        {
            this.ReservedTables = new HashSet<ReservedTable>();
        }
    
        public System.Guid RestaurantId { get; set; }
        public System.Guid Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public string ContactEmail { get; set; }
        public int TotalGuests { get; set; }
    
        public virtual Restaurant Restaurant { get; set; }
        public virtual ICollection<ReservedTable> ReservedTables { get; set; }
    }
}
