//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProjectRestaurangMVC01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurant
    {
        public Restaurant()
        {
            this.ClosedForBookings = new HashSet<ClosedForBooking>();
            this.OpenForBookings = new HashSet<OpenForBooking>();
            this.Reservations = new HashSet<Reservation>();
            this.Tables = new HashSet<Table>();
        }
    
        public int UserId { get; set; }
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public int Zipcode { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public Nullable<int> TotalSeats { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> MaxSeatPerBooking { get; set; }
        public string Rating { get; set; }
        public string Photo { get; set; }
        public string Email { get; set; }
        public bool Activated { get; set; }
    
        public virtual ICollection<ClosedForBooking> ClosedForBookings { get; set; }
        public virtual ICollection<OpenForBooking> OpenForBookings { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual ICollection<Table> Tables { get; set; }
    }
}
