//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupProjectRestaurangMVC01.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public Table()
        {
            this.BookedTables = new HashSet<BookedTable>();
            this.Reservations = new HashSet<Reservation>();
        }
    
        public System.Guid RestaurantId { get; set; }
        public int Id { get; set; }
        public string TableName { get; set; }
        public int Seats { get; set; }
    
        public virtual ICollection<BookedTable> BookedTables { get; set; }
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}
